# Generated by Django 5.0.4 on 2026-06-12 16:07

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_delivery_checkout_totals'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCodeUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
            ],
            options={
                'verbose_name': 'использование промокода',
                'verbose_name_plural': 'использования промокодов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='код')),
                ('discount_type', models.CharField(choices=[('percent', 'Процент'), ('fixed', 'Фиксированная сумма')], max_length=10, verbose_name='тип скидки')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='значение скидки')),
                ('min_order_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='минимальная сумма заказа')),
                ('usage_limit', models.PositiveIntegerField(blank=True, null=True, verbose_name='лимит использований')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='использовано')),
                ('valid_from', models.DateTimeField(blank=True, null=True, verbose_name='действует с')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='действует до')),
                ('is_active', models.BooleanField(default=True, verbose_name='активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлен')),
            ],
            options={
                'verbose_name': 'промокод',
                'verbose_name_plural': 'промокоды',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['code'], name='orders_prom_code_04587b_idx'), models.Index(fields=['is_active'], name='orders_prom_is_acti_cfaf5f_idx'), models.Index(fields=['valid_from'], name='orders_prom_valid_f_96b61c_idx'), models.Index(fields=['valid_until'], name='orders_prom_valid_u_3137cc_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='promocode',
            constraint=models.CheckConstraint(check=models.Q(('value__gt', Decimal('0.00'))), name='promo_code_value_positive'),
        ),
        migrations.AddConstraint(
            model_name='promocode',
            constraint=models.CheckConstraint(check=models.Q(('discount_type', 'fixed'), ('value__lte', Decimal('100.00')), _connector='OR'), name='promo_code_percent_value_lte_100'),
        ),
        migrations.AddConstraint(
            model_name='promocode',
            constraint=models.CheckConstraint(check=models.Q(('min_order_amount__isnull', True), ('min_order_amount__gte', Decimal('0.00')), _connector='OR'), name='promo_code_min_order_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='promocode',
            constraint=models.CheckConstraint(check=models.Q(('usage_limit__isnull', True), ('used_count__lte', models.F('usage_limit')), _connector='OR'), name='promo_code_used_count_lte_limit'),
        ),
        migrations.AddConstraint(
            model_name='promocode',
            constraint=models.CheckConstraint(check=models.Q(('valid_from__isnull', True), ('valid_until__isnull', True), ('valid_until__gte', models.F('valid_from')), _connector='OR'), name='promo_code_valid_until_gte_from'),
        ),
        migrations.AddField(
            model_name='promocodeusage',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='promo_code_usage', to='orders.order', verbose_name='заказ'),
        ),
        migrations.AddField(
            model_name='promocodeusage',
            name='promo_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usages', to='orders.promocode', verbose_name='промокод'),
        ),
        migrations.AddField(
            model_name='promocodeusage',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promo_code_usages', to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
        migrations.AddIndex(
            model_name='promocodeusage',
            index=models.Index(fields=['promo_code'], name='orders_prom_promo_c_48140a_idx'),
        ),
        migrations.AddIndex(
            model_name='promocodeusage',
            index=models.Index(fields=['order'], name='orders_prom_order_i_b4e732_idx'),
        ),
        migrations.AddIndex(
            model_name='promocodeusage',
            index=models.Index(fields=['user'], name='orders_prom_user_id_867860_idx'),
        ),
        migrations.AddIndex(
            model_name='promocodeusage',
            index=models.Index(fields=['created_at'], name='orders_prom_created_45eb83_idx'),
        ),
    ]
