# Generated by Django 5.0.4 on 2026-06-12 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_promocodeusage_promocode_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='promo_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carts', to='orders.promocode', verbose_name='промокод'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['promo_code'], name='orders_cart_promo_c_2dbde2_idx'),
        ),
    ]
