# Generated by Django 5.0.4 on 2026-06-12 16:22

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_cart_promo_code_cart_orders_cart_promo_c_2dbde2_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='сумма скидки'),
        ),
        migrations.AddField(
            model_name='order',
            name='promo_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.promocode', verbose_name='промокод'),
        ),
        migrations.AddField(
            model_name='order',
            name='promo_code_text',
            field=models.CharField(blank=True, max_length=50, verbose_name='код промокода'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['promo_code'], name='orders_orde_promo_c_96f65d_idx'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(check=models.Q(('discount_amount__gte', 0)), name='order_discount_amount_non_negative'),
        ),
    ]
