# Generated by Codex on 2026-06-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_discount_amount_order_promo_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='manager_comment',
            field=models.TextField(blank=True, verbose_name='комментарий менеджера'),
        ),
    ]
