# Generated by Django 5.0.4 on 2026-07-10 10:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_delete_legacy_promo'),
        ('orders', '0010_order_manager_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['payment_status', 'status', 'created_at'], name='order_pay_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order', 'variant'], name='order_item_order_var_idx'),
        ),
    ]
