# Generated by Codex on 2026-06-14

import django.db.models.deletion
from django.db import migrations, models


def create_customer_profiles(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    CustomerProfile = apps.get_model('accounts', 'CustomerProfile')
    profiles = [
        CustomerProfile(user=user)
        for user in User.objects.filter(role='customer').exclude(customer_profile__isnull=False)
    ]
    CustomerProfile.objects.bulk_create(profiles, ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_address_timestamps'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('website', 'Website'), ('instagram', 'Instagram'), ('whatsapp', 'WhatsApp'), ('referral', 'Referral'), ('marketplace', 'Marketplace'), ('offline', 'Offline'), ('other', 'Other')], default='website', max_length=20, verbose_name='источник клиента')),
                ('manager_comment', models.TextField(blank=True, verbose_name='комментарий менеджера')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлен')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to='accounts.user', verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'профиль клиента',
                'verbose_name_plural': 'профили клиентов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='customerprofile',
            index=models.Index(fields=['source'], name='accounts_cu_source_f832a7_idx'),
        ),
        migrations.AddIndex(
            model_name='customerprofile',
            index=models.Index(fields=['created_at'], name='accounts_cu_created_eea5b6_idx'),
        ),
        migrations.RunPython(create_customer_profiles, migrations.RunPython.noop),
    ]
