# Generated by Django 5.0.4 on 2026-07-10 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customerprofile'),
        ('catalog', '0016_delete_legacy_promo'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='wishlist',
            index=models.Index(fields=['user', 'added_at'], name='acct_wish_user_added_idx'),
        ),
        migrations.AddIndex(
            model_name='wishlist',
            index=models.Index(fields=['product', 'added_at'], name='acct_wish_prod_added_idx'),
        ),
    ]
