# Generated by Django 5.0.4 on 2026-07-10 10:31

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0016_delete_legacy_promo'),
        ('orders', '0011_order_order_pay_status_created_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('content', 'Похожие по содержанию'), ('co_purchase', 'Покупают вместе')], max_length=20)),
                ('score', models.DecimalField(decimal_places=8, default=0, max_digits=12)),
                ('support_count', models.PositiveIntegerField(default=0)),
                ('confidence', models.DecimalField(decimal_places=8, default=0, max_digits=12)),
                ('components', models.JSONField(blank=True, default=dict)),
                ('window_started_at', models.DateTimeField(blank=True, null=True)),
                ('window_ended_at', models.DateTimeField(blank=True, null=True)),
                ('calculated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relations', to='catalog.product')),
                ('target_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relations', to='catalog.product')),
            ],
        ),
        migrations.CreateModel(
            name='UserCategoryPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('positive_score', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('negative_score', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('events_count', models.PositiveIntegerField(default=0)),
                ('last_event_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_preferences', to='catalog.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('generation_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('context', models.CharField(choices=[('home', 'Главная'), ('product', 'Товар'), ('cart', 'Корзина'), ('search', 'Поиск'), ('popular', 'Популярное'), ('bought_together', 'Покупают вместе')], max_length=32)),
                ('rank', models.PositiveSmallIntegerField()),
                ('score', models.DecimalField(decimal_places=8, max_digits=18)),
                ('reason_code', models.CharField(max_length=32)),
                ('reason_payload', models.JSONField(blank=True, default=dict)),
                ('algorithm_version', models.CharField(max_length=32)),
                ('is_fallback', models.BooleanField(default=False)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_recommendations', to='catalog.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='UserProductEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anonymous_id_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('event_type', models.CharField(choices=[('view', 'Просмотр'), ('search', 'Поиск'), ('search_click', 'Переход из поиска'), ('favorite_add', 'Добавление в избранное'), ('favorite_remove', 'Удаление из избранного'), ('cart_add', 'Добавление в корзину'), ('cart_remove', 'Удаление из корзины'), ('order_created', 'Заказ создан'), ('purchase', 'Покупка'), ('order_cancel', 'Отмена заказа'), ('return', 'Возврат'), ('rating', 'Оценка'), ('recommendation_impression', 'Показ рекомендации'), ('recommendation_click', 'Клик по рекомендации'), ('recommendation_hide', 'Скрытие рекомендации')], max_length=32)),
                ('source', models.CharField(choices=[('catalog', 'Каталог'), ('search', 'Поиск'), ('wishlist', 'Избранное'), ('cart', 'Корзина'), ('order', 'Заказ'), ('review', 'Отзыв'), ('recommendation', 'Рекомендация')], max_length=32)),
                ('context', models.CharField(blank=True, choices=[('home', 'Главная'), ('product', 'Товар'), ('cart', 'Корзина'), ('search', 'Поиск'), ('popular', 'Популярное'), ('bought_together', 'Покупают вместе')], max_length=32)),
                ('value', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('client_event_id', models.UUIDField(blank=True, null=True, unique=True)),
                ('deduplication_key', models.CharField(blank=True, max_length=160, null=True, unique=True)),
                ('search_query', models.CharField(blank=True, max_length=255, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendation_events', to='orders.orderitem')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_events', to='catalog.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_events', to=settings.AUTH_USER_MODEL)),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendation_events', to='catalog.productvariant')),
                ('recommendation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='recommendations.userrecommendation')),
            ],
            options={
                'ordering': ['-occurred_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='HiddenRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(default='all', max_length=32)),
                ('reason', models.CharField(blank=True, max_length=64)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hidden_by_users', to='catalog.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hidden_recommendations', to=settings.AUTH_USER_MODEL)),
                ('source_recommendation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hide_records', to='recommendations.userrecommendation')),
            ],
        ),
        migrations.CreateModel(
            name='ProductPopularity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('global', 'Глобальная'), ('category', 'По категории')], max_length=16)),
                ('window', models.CharField(choices=[('1d', '1 день'), ('7d', '7 дней'), ('30d', '30 дней'), ('all', 'Всё время')], max_length=8)),
                ('views_count', models.BigIntegerField(default=0)),
                ('search_clicks_count', models.BigIntegerField(default=0)),
                ('favorite_adds_count', models.BigIntegerField(default=0)),
                ('cart_adds_count', models.BigIntegerField(default=0)),
                ('purchases_count', models.BigIntegerField(default=0)),
                ('cancellations_count', models.BigIntegerField(default=0)),
                ('returns_count', models.BigIntegerField(default=0)),
                ('rating_score', models.DecimalField(decimal_places=8, default=0, max_digits=12)),
                ('score', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('window_started_at', models.DateTimeField(blank=True, null=True)),
                ('window_ended_at', models.DateTimeField(blank=True, null=True)),
                ('calculated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_popularity_rows', to='catalog.category')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='popularity_rows', to='catalog.product')),
            ],
            options={
                'indexes': [models.Index(fields=['scope', 'category', 'window', '-score'], name='reco_pop_scope_score_idx'), models.Index(fields=['product', 'window'], name='reco_pop_product_win_idx'), models.Index(fields=['calculated_at'], name='reco_pop_calculated_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='productpopularity',
            constraint=models.UniqueConstraint(condition=models.Q(('category__isnull', True)), fields=('product', 'scope', 'window'), name='reco_pop_global_uniq'),
        ),
        migrations.AddConstraint(
            model_name='productpopularity',
            constraint=models.UniqueConstraint(condition=models.Q(('category__isnull', False)), fields=('product', 'category', 'scope', 'window'), name='reco_pop_category_uniq'),
        ),
        migrations.AddConstraint(
            model_name='productpopularity',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('category__isnull', True), ('scope', 'global')), models.Q(('category__isnull', False), ('scope', 'category')), _connector='OR'), name='reco_pop_scope_category_ck'),
        ),
        migrations.AddIndex(
            model_name='productrelation',
            index=models.Index(fields=['source_product', 'relation_type', '-score'], name='reco_relation_source_idx'),
        ),
        migrations.AddIndex(
            model_name='productrelation',
            index=models.Index(fields=['target_product', 'relation_type'], name='reco_relation_target_idx'),
        ),
        migrations.AddConstraint(
            model_name='productrelation',
            constraint=models.UniqueConstraint(fields=('source_product', 'target_product', 'relation_type'), name='reco_relation_pair_uniq'),
        ),
        migrations.AddConstraint(
            model_name='productrelation',
            constraint=models.CheckConstraint(check=models.Q(('source_product', models.F('target_product')), _negated=True), name='reco_relation_not_self_ck'),
        ),
        migrations.AddIndex(
            model_name='usercategorypreference',
            index=models.Index(fields=['user', '-score'], name='reco_pref_user_score_idx'),
        ),
        migrations.AddIndex(
            model_name='usercategorypreference',
            index=models.Index(fields=['category', '-score'], name='reco_pref_category_idx'),
        ),
        migrations.AddIndex(
            model_name='usercategorypreference',
            index=models.Index(fields=['last_event_at'], name='reco_pref_last_event_idx'),
        ),
        migrations.AddConstraint(
            model_name='usercategorypreference',
            constraint=models.UniqueConstraint(fields=('user', 'category'), name='reco_user_category_uniq'),
        ),
        migrations.AddIndex(
            model_name='userrecommendation',
            index=models.Index(fields=['user', 'context', '-generated_at'], name='reco_user_ctx_gen_idx'),
        ),
        migrations.AddIndex(
            model_name='userrecommendation',
            index=models.Index(fields=['user', 'context', 'generation_id', 'rank'], name='reco_user_gen_rank_idx'),
        ),
        migrations.AddIndex(
            model_name='userrecommendation',
            index=models.Index(fields=['expires_at'], name='reco_user_expires_idx'),
        ),
        migrations.AddIndex(
            model_name='userrecommendation',
            index=models.Index(fields=['generation_id'], name='reco_generation_idx'),
        ),
        migrations.AddConstraint(
            model_name='userrecommendation',
            constraint=models.UniqueConstraint(fields=('user', 'context', 'generation_id', 'product'), name='reco_user_gen_product_uniq'),
        ),
        migrations.AddConstraint(
            model_name='userrecommendation',
            constraint=models.UniqueConstraint(fields=('user', 'context', 'generation_id', 'rank'), name='reco_user_gen_rank_uniq'),
        ),
        migrations.AddIndex(
            model_name='userproductevent',
            index=models.Index(fields=['user', '-occurred_at'], name='reco_event_user_time_idx'),
        ),
        migrations.AddIndex(
            model_name='userproductevent',
            index=models.Index(fields=['product', 'event_type', '-occurred_at'], name='reco_event_product_type_idx'),
        ),
        migrations.AddIndex(
            model_name='userproductevent',
            index=models.Index(fields=['event_type', '-occurred_at'], name='reco_event_type_time_idx'),
        ),
        migrations.AddIndex(
            model_name='userproductevent',
            index=models.Index(fields=['anonymous_id_hash', '-occurred_at'], name='reco_event_anon_time_idx'),
        ),
        migrations.AddIndex(
            model_name='userproductevent',
            index=models.Index(fields=['source', 'context', '-occurred_at'], name='reco_event_source_ctx_idx'),
        ),
        migrations.AddConstraint(
            model_name='userproductevent',
            constraint=models.CheckConstraint(check=models.Q(('user__isnull', False), models.Q(('anonymous_id_hash', ''), _negated=True), _connector='OR'), name='reco_event_actor_required'),
        ),
        migrations.AddConstraint(
            model_name='userproductevent',
            constraint=models.CheckConstraint(check=models.Q(('event_type', 'search'), ('product__isnull', False), _connector='OR'), name='reco_event_product_required'),
        ),
        migrations.AddIndex(
            model_name='hiddenrecommendation',
            index=models.Index(fields=['user', 'context', 'expires_at'], name='reco_hidden_user_ctx_idx'),
        ),
        migrations.AddIndex(
            model_name='hiddenrecommendation',
            index=models.Index(fields=['product'], name='reco_hidden_product_idx'),
        ),
        migrations.AddConstraint(
            model_name='hiddenrecommendation',
            constraint=models.UniqueConstraint(fields=('user', 'product', 'context'), name='reco_hidden_user_product_uniq'),
        ),
    ]
