# Generated by Django 5.0.4 on 2026-06-08 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('stripe', 'Stripe'), ('kaspi', 'Kaspi Pay'), ('freedom', 'Freedom Pay'), ('cod', 'Наличными при получении')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('success', 'Успешно'), ('failed', 'Ошибка'), ('refunded', 'Возврат')], default='pending', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='KZT', max_length=3)),
                ('provider_payment_id', models.CharField(blank=True, max_length=255)),
                ('provider_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order')),
            ],
            options={
                'verbose_name': 'платёж',
                'verbose_name_plural': 'платежи',
                'ordering': ['-created_at'],
            },
        ),
    ]
