# Generated by Codex on 2026-06-12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_update_review_moderation_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='button_text',
            field=models.CharField(blank=True, max_length=100, verbose_name='текст кнопки'),
        ),
        migrations.AddField(
            model_name='banner',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name='создан',
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banner',
            name='updated_at',
            field=models.DateTimeField(
                auto_now=True,
                default=django.utils.timezone.now,
                verbose_name='обновлен',
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='banner',
            name='ends_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='окончание показа'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(upload_to='banners/%Y/%m/%d/', verbose_name='изображение'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image_mobile',
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to='banners/%Y/%m/%d/',
                verbose_name='мобильное изображение',
            ),
        ),
        migrations.AlterField(
            model_name='banner',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='активен'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='link',
            field=models.CharField(blank=True, max_length=255, verbose_name='ссылка'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='порядок'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='starts_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='начало показа'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='subtitle',
            field=models.CharField(blank=True, max_length=300, verbose_name='подзаголовок'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(max_length=200, verbose_name='заголовок'),
        ),
        migrations.AlterModelOptions(
            name='banner',
            options={
                'ordering': ['sort_order', 'id'],
                'verbose_name': 'баннер',
                'verbose_name_plural': 'баннеры',
            },
        ),
        migrations.AddIndex(
            model_name='banner',
            index=models.Index(fields=['is_active'], name='catalog_banner_active_idx'),
        ),
        migrations.AddIndex(
            model_name='banner',
            index=models.Index(fields=['sort_order'], name='catalog_banner_sort_idx'),
        ),
    ]
