# Generated by Django 5.0.4 on 2026-06-13 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_update_banner_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='catalog/imports/%Y/%m/%d/', verbose_name='CSV файл')),
                ('status', models.CharField(choices=[('pending', 'Ожидает обработки'), ('processing', 'В обработке'), ('completed', 'Завершён'), ('completed_with_errors', 'Завершён с ошибками'), ('failed', 'Ошибка')], default='pending', max_length=32, verbose_name='статус')),
                ('total_count', models.PositiveIntegerField(default=0, verbose_name='всего строк')),
                ('success_count', models.PositiveIntegerField(default=0, verbose_name='успешно')),
                ('failed_count', models.PositiveIntegerField(default=0, verbose_name='с ошибками')),
                ('error_report', models.JSONField(blank=True, default=list, verbose_name='отчёт об ошибках')),
                ('error_message', models.CharField(blank=True, max_length=500, verbose_name='фатальная ошибка')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='начата')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='завершена')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлена')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_import_jobs', to=settings.AUTH_USER_MODEL, verbose_name='загрузил')),
            ],
            options={
                'verbose_name': 'импорт товаров',
                'verbose_name_plural': 'импорты товаров',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportJobError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField(verbose_name='номер строки')),
                ('row_data', models.JSONField(blank=True, default=dict, verbose_name='данные строки')),
                ('error_message', models.TextField(verbose_name='ошибка')),
                ('field_errors', models.JSONField(blank=True, default=dict, verbose_name='ошибки полей')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создана')),
                ('import_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='catalog.importjob', verbose_name='импорт')),
            ],
            options={
                'verbose_name': 'ошибка импорта товаров',
                'verbose_name_plural': 'ошибки импорта товаров',
                'ordering': ['import_job', 'row_number', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='importjob',
            index=models.Index(fields=['status'], name='catalog_imp_status_77888b_idx'),
        ),
        migrations.AddIndex(
            model_name='importjob',
            index=models.Index(fields=['created_by'], name='catalog_imp_created_909ee3_idx'),
        ),
        migrations.AddIndex(
            model_name='importjob',
            index=models.Index(fields=['created_at'], name='catalog_imp_created_5fa5c3_idx'),
        ),
        migrations.AddIndex(
            model_name='importjoberror',
            index=models.Index(fields=['import_job'], name='catalog_imp_import__a08f76_idx'),
        ),
        migrations.AddIndex(
            model_name='importjoberror',
            index=models.Index(fields=['row_number'], name='catalog_imp_row_num_8498e9_idx'),
        ),
    ]
