# Generated by Django 5.0.4 on 2026-06-13 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_importjob_importjoberror_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importjob',
            name='error_report',
            field=models.JSONField(blank=True, null=True, verbose_name='отчёт об ошибках'),
        ),
    ]
