# Generated by Codex on 2026-06-12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=220, unique=True, verbose_name='slug')),
                ('title', models.CharField(max_length=200, verbose_name='название')),
                ('content', models.TextField(verbose_name='контент')),
                ('seo_title', models.CharField(blank=True, max_length=200, verbose_name='SEO title')),
                ('seo_description', models.TextField(blank=True, verbose_name='SEO description')),
                ('is_active', models.BooleanField(default=True, verbose_name='активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлена')),
            ],
            options={
                'verbose_name': 'статическая страница',
                'verbose_name_plural': 'статические страницы',
                'ordering': ['title'],
                'indexes': [
                    models.Index(fields=['slug'], name='cms_static_slug_idx'),
                    models.Index(fields=['is_active'], name='cms_static_active_idx'),
                ],
            },
        ),
    ]
